#!/bin/sh
# ─── Mydow nginx entrypoint with HTTPS auto-enable ───────────────────────
#
# todo-tasks.md §11.3 (Owner: Agent / my-mcp-20 @ 2026-05-06)
#
# Behaviour:
#   1. If /etc/nginx/ssl/{fullchain.pem,privkey.pem} both exist → serve both
#      :80 (acme + 301 to https) and :443 (TLS) per docker/nginx/mydow.conf.
#   2. Otherwise → strip the :443 server block via nginx -t / sed so we
#      don't crash on missing cert. The :80 server keeps serving directly.
#   3. Always validate config with `nginx -t` before exec.
#
# This keeps the same docker image / compose file usable in dev (no certs)
# and prod (real certs) without manual edits.
# ─────────────────────────────────────────────────────────────────────────

set -e

CONF="/etc/nginx/conf.d/default.conf"
CERT="/etc/nginx/ssl/fullchain.pem"
KEY="/etc/nginx/ssl/privkey.pem"

if [ -f "$CERT" ] && [ -f "$KEY" ]; then
    echo "[mydow-nginx] HTTPS certs found at $CERT — enabling :443 server"
    HTTPS_ENABLED=1
else
    echo "[mydow-nginx] no HTTPS certs at $CERT — disabling :443 server (dev mode)"
    HTTPS_ENABLED=0

    # Strip the entire `server { listen 443 ssl ... }` block. We don't have
    # a perl / awk dependency in alpine; use a lightweight sed pipeline:
    #   1) strip every line from the marker comment to end-of-file
    #   2) keep the file head (HTTP server only)
    #
    # The marker is the literal `# ─── HTTPS server` comment in mydow.conf.
    if grep -q "HTTPS server (port 443)" "$CONF"; then
        # Make a tmp copy in /tmp (CONF is mounted ro)
        cp "$CONF" /tmp/default.conf
        sed -i '/HTTPS server (port 443)/,$d' /tmp/default.conf
        # Re-mount the conf via a writable bind-mount path nginx will read.
        # Simpler: write the cleaned file to a different location and tell
        # nginx to use it.
        cp /tmp/default.conf /etc/nginx/conf.d/default.conf.runtime
        # nginx looks at /etc/nginx/conf.d/*.conf — rename original to .conf.disabled
        # Note: CONF is mounted read-only, so `mv` would EROFS. We work around
        # by replacing the include via env: not possible without a wrapper conf.
        # Instead: write a minimal http server include and make nginx pick the
        # smaller one first via filename ordering (alphabetical loading order).
        cat > /etc/nginx/conf.d/00-default-no-tls.conf <<EOF
# Generated by entrypoint.sh — HTTPS disabled (no cert)
upstream mydow_app {
    server app:8000;
    keepalive 32;
}

map \$request_uri \$is_hashed_asset {
    default                 0;
    "~*\\.[a-f0-9]{8,}\\..*\$" 1;
}

limit_req_zone \$binary_remote_addr zone=auth_zone:10m  rate=10r/m;
limit_req_zone \$binary_remote_addr zone=ai_zone:10m    rate=30r/m;
limit_req_zone \$binary_remote_addr zone=search_zone:10m rate=120r/m;

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type "text/plain";
        try_files \$uri =404;
    }

    include /etc/nginx/conf.d/locations.conf.inc;
}
EOF
        # Disable the original conf so nginx doesn't try to start :443.
        # The mounted file is read-only, so we override by removing the
        # symlink (if present) — actually conf.d is a writable dir even
        # when the file is ro-mounted, so `rm` of a ro file fails on Linux
        # but the directory listing is mutable. We overwrite the file
        # name in nginx loading: alphabetical: 00-...conf wins precedence
        # because nginx reads files in order and our default.conf still
        # has :80, but :443 would also start. The cleanest way is to
        # rename via cp + remove inability. Since we can't remove the ro
        # file, we modify nginx.conf to skip the conf.d include for it.
        #
        # Alpine nginx's nginx.conf has `include /etc/nginx/conf.d/*.conf;`.
        # We can't easily exclude one file. So instead: write a wrapper
        # conf that uses `if` to decline :443 — but that's not allowed
        # at server-start.
        #
        # Pragmatic solution: rewrite nginx.conf to include only
        # 00-default-no-tls.conf when no TLS:
        sed -i 's|include /etc/nginx/conf.d/\*.conf;|include /etc/nginx/conf.d/00-default-no-tls.conf;|' /etc/nginx/nginx.conf
        echo "[mydow-nginx] swapped nginx.conf include → 00-default-no-tls.conf only"
    fi
fi

# Validate
echo "[mydow-nginx] testing config..."
nginx -t

# Hand off to the standard nginx entrypoint chain (signal handling etc.)
echo "[mydow-nginx] starting nginx (HTTPS_ENABLED=$HTTPS_ENABLED)"
exec nginx -g 'daemon off;'
