"""Stage 3 Models - AgentDecision, Skill, TaskExecutionLog.

These models support multi-step Agent workflows, user decisions, and skill abstraction.
Note: We use AgentDecision instead of DecisionPoint to avoid conflict with items.models.DecisionPoint
"""

import uuid
from datetime import datetime
from sqlalchemy import Column, String, Text, DateTime, ForeignKey, JSON, Integer, Boolean, Index
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from agent_os.db.base import Base


class AgentDecision(Base):
    """Agent Decision - Records structured decision options generated by Agent.

    Used when Agent needs user confirmation at key steps in the workflow.
    This is Stage 3 specific and different from items.models.DecisionPoint (PRD4).
    """

    __tablename__ = "agent_decisions"

    # Primary key
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)

    # Foreign keys - Note: We'll use task_id as UUID string for now
    # until Task model is migrated to UUID
    task_id = Column(String(36), nullable=False, index=True)  # Task UUID as string
    step_name = Column(String(100), nullable=False)  # e.g., "step_2_generate_options"

    # Decision options (JSON structure)
    options = Column(JSON, nullable=False)
    # Example:
    # [
    #   {
    #     "id": "option_a",
    #     "title": "Accept Project",
    #     "description": "High ROI and manageable risk",
    #     "rationale": "ROI > 50%, risk score < 3",
    #     "risks": ["Requires 20 person-months"],
    #     "confidence": 0.85
    #   }
    # ]

    # User selection
    selected_option_id = Column(String(100), nullable=True)  # User's choice
    confirmed_at = Column(DateTime(timezone=True), nullable=True)  # Confirmation time
    confirmed_by = Column(String(36), nullable=True)  # User UUID as string

    # Timestamps
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

    # Indexes
    __table_args__ = (
        Index('idx_agent_decision_task_step', 'task_id', 'step_name'),
        Index('idx_agent_decision_status', 'task_id', 'selected_option_id'),
    )


class Skill(Base):
    """Skill Model - Reusable Agent workflow definition.

    Represents a multi-step Agent process that can be applied to different tasks.
    """

    __tablename__ = "skills"

    # Primary key
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)

    # Basic info
    name = Column(String(200), nullable=False)  # e.g., "Career Decision Assistant"
    description = Column(Text)  # Skill description
    category = Column(String(50), nullable=False)  # decision, analysis, synthesis

    # Skill definition (core)
    steps = Column(JSON, nullable=False)
    # Example:
    # [
    #   {
    #     "order": 1,
    #     "name": "analyze_context",
    #     "description": "Analyze decision context",
    #     "agent_action": "classify_and_summarize",
    #     "requires_confirmation": false,
    #     "output_schema": {"context_type", "priority", "complexity"}
    #   },
    #   {
    #     "order": 2,
    #     "name": "generate_options",
    #     "description": "Generate decision options",
    #     "agent_action": "generate_decision_options",
    #     "requires_confirmation": true,
    #     "output_schema": {"options": [], "recommended_option_id"}
    #   }
    # ]

    # Applicable scenarios
    applicable_item_types = Column(JSON)  # ["task", "decision"]
    min_confidence = Column(String(20), default="medium")  # low, medium, high
    required_tags = Column(JSON)  # ["career", "project"]

    # Version control
    version = Column(String(20), nullable=False, default="1.0")
    parent_skill_id = Column(UUID(as_uuid=True), ForeignKey("skills.id"))

    # Creation info
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    created_by = Column(String(36), nullable=True)  # User UUID as string
    is_active = Column(Boolean, default=True)  # Soft delete

    # Relationships
    parent_skill = relationship("Skill", remote_side=[id], backref="versions")

    # Indexes
    __table_args__ = (
        Index('idx_skill_category', 'category', 'is_active'),
        Index('idx_skill_version', 'id', 'version'),
    )


class TaskExecutionLog(Base):
    """Task Execution Log - Records each step of Agent Flow execution.

    Provides full traceability and replay capability for Agent workflows.
    """

    __tablename__ = "task_execution_logs"

    # Primary key
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)

    # Foreign keys
    task_id = Column(String(36), nullable=False, index=True)  # Task UUID as string
    decision_id = Column(UUID(as_uuid=True), ForeignKey("agent_decisions.id"), nullable=True)

    # Step information
    step_name = Column(String(100), nullable=False)  # Corresponds to Skill.steps[].name
    step_order = Column(Integer, nullable=False)  # Execution order

    # Input/Output
    input_data = Column(JSON)  # Step input
    output_data = Column(JSON)  # Step output

    # Execution info
    status = Column(String(20), nullable=False)  # pending, running, completed, failed, waiting_confirmation
    started_at = Column(DateTime(timezone=True))
    completed_at = Column(DateTime(timezone=True))
    duration_ms = Column(Integer)  # Execution duration in milliseconds

    # Error info
    error_message = Column(Text)
    error_stack = Column(Text)

    # Agent info
    agent_action = Column(String(100))  # Executed Agent action
    agent_version = Column(String(20))  # Agent version

    # Timestamps
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    # Relationships
    decision = relationship("AgentDecision", foreign_keys=[decision_id])

    # Indexes
    __table_args__ = (
        Index('idx_exec_log_task_step', 'task_id', 'step_order'),
        Index('idx_exec_log_status', 'task_id', 'status'),
        Index('idx_exec_log_decision', 'decision_id'),
    )
