param(
    [switch]$NoOpen,
    [switch]$NoBuild,
    [switch]$NoSeed,
    [int]$Port = 8000
)

$ErrorActionPreference = "Stop"

$Root = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$EnvFile = Join-Path $Root ".env.docker.local"
$ComposeFile = Join-Path $Root "docker-compose.prd10.yml"
$FrontendUrl = "http://localhost:$Port/mydow/"
$HealthUrl = "http://localhost:$Port/health"

function Get-ProjectEnvValue {
    param([string]$Name)
    $processValue = [Environment]::GetEnvironmentVariable($Name)
    if ($processValue) { return $processValue }

    $sourceEnv = Join-Path $Root ".env"
    if (-not (Test-Path $sourceEnv)) { return "" }

    foreach ($line in Get-Content $sourceEnv) {
        if ($line -match "^\s*$([regex]::Escape($Name))\s*=\s*(.*)\s*$") {
            $value = $Matches[1].Trim()
            if (($value.StartsWith('"') -and $value.EndsWith('"')) -or ($value.StartsWith("'") -and $value.EndsWith("'"))) {
                $value = $value.Substring(1, $value.Length - 2)
            }
            return $value
        }
    }
    return ""
}

function New-Secret {
    return ([Guid]::NewGuid().ToString("N") + [Guid]::NewGuid().ToString("N"))
}

function Ensure-DockerEnv {
    if (Test-Path $EnvFile) {
        Write-Host "[mydow] using existing $EnvFile"
        return
    }

    $apiKey = Get-ProjectEnvValue "API_KEY"
    if (-not $apiKey) { $apiKey = Get-ProjectEnvValue "DEEPSEEK_API_KEY" }
    $apiBase = Get-ProjectEnvValue "API_BASE"
    $model = Get-ProjectEnvValue "MODEL"
    $modelFallback = Get-ProjectEnvValue "MODEL_FALLBACK"
    if (-not $modelFallback) { $modelFallback = "GLM-4-Flash" }

    $content = @(
        "# Generated by run-mydow.cmd. Do not commit this file.",
        "SECRET_KEY=$(New-Secret)",
        "JWT_SECRET_KEY=$(New-Secret)",
        "FIELD_ENCRYPTION_KEY=",
        "DATABASE_URL=sqlite+aiosqlite:////app/data/mydow.db",
        "AGENTOS_DEMO_MODE=on",
        "AGENTOS_PRD10_WORKER=on",
        "AGENTOS_AI_LLM=on",
        "AGENTOS_AI_TEMPERATURE=0.3",
        "AGENTOS_AI_MAX_TOKENS=1000",
        "API_KEY=$apiKey",
        "API_BASE=$apiBase",
        "MODEL=$model",
        "MODEL_FALLBACK=$modelFallback",
        "CAPTURE_ENRICH_MODEL=",
        "APP_PORT=$Port",
        "BASE_URL=http://localhost:$Port",
        "CORS_ORIGINS=http://localhost:$Port,http://127.0.0.1:$Port",
        "POSTGRES_USER=agentos",
        "POSTGRES_PASSWORD=agentos",
        "POSTGRES_DB=agentos_db",
        "POSTGRES_HOST_PORT=15432",
        "REDIS_PASSWORD=redis123",
        "REDIS_HOST_PORT=16379",
        "ENVIRONMENT=production",
        "LOG_LEVEL=info"
    )
    Set-Content -LiteralPath $EnvFile -Value $content -Encoding UTF8
    Write-Host "[mydow] generated $EnvFile"
    if (-not $apiKey) {
        Write-Host "[mydow] warning: no API_KEY/DEEPSEEK_API_KEY found in environment or .env; LLM endpoints need a real key." -ForegroundColor Yellow
    }
}

function Invoke-Compose {
    param([string[]]$ComposeArgs)
    & docker compose --env-file $EnvFile -f $ComposeFile @ComposeArgs
    if ($LASTEXITCODE -ne 0) {
        throw "docker compose failed: $($ComposeArgs -join ' ')"
    }
}

function Wait-Healthy {
    Write-Host "[mydow] waiting for backend health: $HealthUrl"
    for ($i = 1; $i -le 90; $i++) {
        try {
            $resp = Invoke-RestMethod -Uri $HealthUrl -TimeoutSec 3
            if ($resp.status -eq "healthy") {
                Write-Host "[mydow] backend is healthy"
                return
            }
        } catch {
            Start-Sleep -Seconds 2
        }
    }
    Invoke-Compose @("logs", "--tail", "120", "app")
    throw "backend did not become healthy"
}

Set-Location $Root

try {
    # `docker info` can write engine warnings to stderr and make `$?` false
    # even with exit code 0 on Windows PowerShell. `docker ps` is the quiet
    # availability probe we actually need here.
    & docker ps 1>$null 2>$null
    $dockerOk = ($LASTEXITCODE -eq 0)
} catch {
    $dockerOk = $false
}
if (-not $dockerOk) {
    Write-Host "[mydow] Docker is not running. Start Docker Desktop and rerun run-mydow.cmd." -ForegroundColor Red
    exit 1
}

Ensure-DockerEnv

$upArgs = @("up", "-d")
if (-not $NoBuild) { $upArgs += "--build" }
$upArgs += @("app", "postgres", "redis")
Invoke-Compose $upArgs

Wait-Healthy

if (-not $NoSeed) {
    Write-Host "[mydow] seeding demo data into the real persisted database"
    Invoke-Compose @("exec", "-T", "app", "python", "scripts/seed_prd10.py")
}

Write-Host ""
Write-Host "[mydow] ready: $FrontendUrl" -ForegroundColor Green
Write-Host "[mydow] stop:  docker compose --env-file .env.docker.local -f docker-compose.prd10.yml down"
Write-Host ""

if (-not $NoOpen) {
    Start-Process $FrontendUrl
}
